### ISSUE TITLE
localisedName used for heading, name used for page title

### ISSUE THREAD

**Issue by mfortini** [italia/developers.italia.it#1026]
publiccode.yml can show a `localisedName` which is different from the `name` attribute.

Currently, the portal uses `name` as the page title, while it uses `localisedName` as the heading.

This can be confusing, e.g. in this case https://developers.italia.it/it/software/c_a944-comunebologna-mappalavoristradali

![immagine](https://user-images.githubusercontent.com/1104926/124153742-0bed1080-da95-11eb-9a43-8f136d8f84de.png)

**Comment by bfabio** [comment]
@mfortini looks like this is not easy as I thought because of the way Jekyll handles includes and templating (`head.html` gets included before the page content and AFAIK there is no clean way to set the title from the page context).

I'd keep this open to track the issue (maybe #1007 would fix it) and have them fix the publiccode.yml.

**Comment by bfabio** [comment]
https://github.com/jekyll/jekyll/issues/4370

I'd say the only way we can get this feature is through Javascript :/
