### ISSUE TITLE
The software filter UI should be localized

### ISSUE THREAD

**Issue by bfabio** [italia/developers.italia.it#1304]
The [software filter UI](https://developers.italia.it/it/search) is not localized in the Italian version of the site:

![image](https://user-images.githubusercontent.com/788293/186682062-ab49eb9b-0218-41b7-8af2-6df639c024b6.png)

**Comment by Pyr0x1** [comment]
Hello, I could work on this with a bit more info on how to do it

**Comment by bfabio** [comment]
@Pyr0x1 sorry for the late reply, are you still up for it?

It' should just be a matter of localizing the categories strings here: https://github.com/italia/developers.italia.it/blob/master/_data/l10n.yml#L309

**Comment by ChrisUser** [comment]
Hi @bfabio, since @Pyr0x1 hasn't responded for 2 weeks I thought I'll address this issue myself.

I've already read the guidelines and made a fork of this project. I'm currently working on the localizations but, after that, you also need me to sort all the keys in alphabetical order or this will be done automatically by the system?
The other localized keys don't seem sorted alphabetically, but I'm asking to be sure.

**Comment by ChrisUser** [comment]
Ok, after a couple of attempts I was able to start the project locally. However, I noticed that by updating the [l10n.yml](https://github.com/italia/developers.italia.it/blob/master/_data/l10n.yml#L309) file only the categories in the homepage became localized and **not sorted in alphabetical order**.

Investigating further I found that the categories in the search screen are taken from a different file ([publiccode_categories.yml](https://github.com/italia/developers.italia.it/blob/master/_data/publiccode_categories.yml)). I'll try to understand better how the system works before opening the pull request since I believe there will be more than one file to change.

**Comment by bfabio** [comment]
Hi @ChrisUser, yes, we should keep the labels ordered alphabetically, but it can be in a different PR if you prefer.

Note that ` publiccode_categories.yml` just defines the category tags from the [publiccode.yml format](https://yml.publiccode.tools/categories-list.html) and should not be localized.

**Comment by ChrisUser** [comment]
I've created the PR with the correct localization and sorting of the entries in the 'software filter' page, which will do the job for this issue.
However I wasn't able to sort the category labels in the home page inside [home-software-categories.html](https://github.com/italia/developers.italia.it/blob/master/_includes/home-software-categories.html#L6). I've understood how the sort filter works in Jekyll but none of my attempts worked.

Maybe someone who knows Jekyll better than me can finally solve this last piece of the puzzle.

**Comment by bfabio** [comment]
@ChrisUser we can tackle the sorting in the home page in another issue, thank you!
