### ISSUE TITLE
Software screenshots cannot be enlarged

### ISSUE THREAD

**Issue by alranel** [italia/developers.italia.it#267]
There's a bug with the Photoswipe JS library used for enlarging screenshots in the software pages: the modal window is not rendered correctly.

**Comment by alranel** [comment]
I temporarily disabled Photoswipe until we can work on this issue. Screenshots are now opened directly via regular links, which is not optimal but better than the buggy behavior.

**Comment by sebbalex** [comment]
Reactivated Photoswipe. Unexpected behaviour was due to undefined size of images. Now they are calculated directly from DOM.
Still under investigation this [data-size fileds](https://github.com/italia/developers.italia.it/blob/2312a5ba1b1f0877e50aff611485d5cfb8c96058/_includes/tiled-gallery.html#L5) which contains the unset `image` variable
