### ISSUE TITLE
Bug: wrong og title for software catalogue pages

### ISSUE THREAD

**Issue by alranel** [italia/developers.italia.it#327]
The `slug` field is used in the og:title field of the software catalogue, which is not good. We should show something like `Developers Italia - <software name>`.

**Comment by sebbalex** [comment]
og:title is created by [jekyll-seo-tag](https://github.com/jekyll/jekyll-seo-tag) which use `page.title` var to populate title tags.

Pages under software are created by [datepage_gen](https://github.com/avillafiorita/jekyll-datapage_gen) plugin where `page.title` tag is set to `data[name]` with `name` set to `slug` [here](https://github.com/italia/developers.italia.it/blob/master/_config.yml#L171) .

Since `name` in `_config.yml` is used to generate filename too and we cannot change it. Last chance we have is to modify that plugin (which is included in project) to act as we need.

**Comment by sebbalex** [comment]
As discussed offline go for last chance, modifying plugin as for our needs.
