### ISSUE TITLE
Tweak the recommendation system logic

### ISSUE THREAD

**Issue by libremente** [italia/developers.italia.it#397]
As of today, the reccommended software section is not working as expected. In fact, the same software are shown over every page. I would suggest improving it for example exploiting the score returned by elasticsearch. 
However, which are the intended keywords to perform such a search? 
@sebbalex

**Comment by libremente** [comment]
Some may be:
* Categories
* Platforms
* License?
* Dependencies?
Does it make sense to use also the "usedBy" values to reccomend a software? Or something like "PA "A" also uses..."?

**Comment by sebbalex** [comment]
Here we have two situations:
1. recommendation system is not working https://github.com/italia/developers.italia.it/issues/601
2. which parameter are used to filter softwares

First case is fixed with https://github.com/italia/developers-italia-backend/pull/177
Second: as of now softwares are filtered using categories and sorted by score descending. This process is inside the crawler and starts at the final phase (file generation), it cycles all softwares in elasticsearch and for everyone get its related by filtering for almost same categories. Query is using `Should` filter which try to filter if any results match or returns similar items with higher score.

more details here: https://github.com/italia/developers-italia-backend/blob/master/crawler/jekyll/softwares.go#L179:L181

**Comment by bfabio** [comment]
IMO that's good enough for this issue. We can always improve it after the global UX rework. @libremente WDYT?

**Comment by libremente** [comment]
Ok makes sense, let's consider this one closed after the merge of your work @sebbalex

**Comment by sebbalex** [comment]
> Ok makes sense, let's consider this one closed @sebbalex

already merged: https://github.com/italia/developers-italia-backend/pull/177

Closing!
Thanks
