### ISSUE TITLE
Tagline/agenda of Developers Italia also getting selected if hovered over the logo.

### ISSUE THREAD

**Issue by ritikasource** [italia/developers.italia.it#491]
Once we hover over the icon the tagline also gets selected along with the logo title and that could be unselected to improve the UI.

**Comment by libremente** [comment]
Hi @ritikasource and thanks for your contribution!
I personally don't like this a lot as well, however I have to investigate the origin of such a behavior (it could be provided in the mockups). I'll get back to you!

**Comment by ritikasource** [comment]
Hey @libremente glad that you considered also I would definitely like to help to fix this issue.

**Comment by libremente** [comment]
Hi @ritikasource , feel free to work on this issue

**Comment by bfabio** [comment]
Hello @ritikasource, any news on this?

**Comment by namrataaaa** [comment]
Hi! I found the solution to this problem and I will be able to fix it. I was able to identify and solve this issue by inspecting the web page but I was unable to find the HTML file in the project. I apologise for this because I am not well acquainted with this kind of structure. So if you can assign this task to me and direct me to where I can find the HTML file, I'll be very grateful.
