### ISSUE TITLE
Switch to Jekyll 4.x

### ISSUE THREAD

**Issue by libremente** [italia/developers.italia.it#623]
We should switch to Jekyll 4.x

**Comment by UchihaCFC** [comment]
Can I do this? :) 

I update it to latest version (4.1.1 now)?

**Comment by libremente** [comment]
Hi @UchihaCFC, if you feel like trying I guess you can give it a go. Please keep in mind that we are deploying through GH pages, so I believe the upgrade won't be very straightforward... see this https://github.com/github/pages-gem/issues/651 for example. I'm not sure GH is currently fully supporting Jekyl 4.x.x

**Comment by UchihaCFC** [comment]
@libremente hahaha I see, I try to update and testing that everything works correctly after that. If I think it's too complicated or I can't do it, I'll let you know 👍🏼

**Comment by UchihaCFC** [comment]
It seems that there are no problems updating to version 4.1.1 of Jekyll. With the exception of hawkins, but I have seen that it is not necessary to continue using it because version 4 includes live reload, so I have removed it to continue with the update. You can see more about it here: awood/hawkins#17

When doing the `docker-compose up --build` I have seen that it generates new jekyll cache files in the `.jekyll-cache` folder, so I have added it to the `.gitignore` file.

After all I have run `docker-compose up` and everything seems to work fine.

This is the commit(UchihaCFC@375d447),  if you don't see it very badly, I do the pull request, but I preferred to consult you before doing it.

**Comment by bfabio** [comment]
@UchihaCFC Thanks, it all makes sense. Let's see how the Netlify preview looks like on a PR :+1:

**Comment by UchihaCFC** [comment]
@bfabio just did an `origin/master` merge where I was working and a pull request, fingers crossed! 🤞
