### ISSUE TITLE
API pages marked as "coming soon" should not be indexed

### ISSUE THREAD

**Issue by libremente** [italia/developers.italia.it#678]
**Describe the bug**

Right now API pages marked as "Coming Soon" are indexed and returned via search bar. Try https://developers.italia.it/it/api/trasporti-opendata.html for example. This page should not be indexed and should not show up.

**To Reproduce**
1. Go to Search Bar
2. Search for "opendata"
3. Click the result
4. You are seeing a page that should not be seen

**Expected behavior**

Those pages should not be indexed and visible.

**Comment by ccatterina** [comment]
Hi, can I work on this?

**Comment by libremente** [comment]
@ccatterina sure! Assigning this to you :+1: thanks a lot for your time!

**Comment by ccatterina** [comment]
I have a doubt, do you want the API pages marked as `comingsoon` to be filtered out using the `elasticsearch` query or do you prefer that they are not indexed by the `elasticsearch` engine?

**Comment by bfabio** [comment]
On a second thought: we'd lose information not returning it in the search. As a user I appreciate being told that something is coming soon more than having no information at all.

I think the root issue is that `comingsoon` pages should have the usual description, a coming soon badge and no swagger UI, instead of just the current "No API definition provided" message.

@libremente wdyt?

**Comment by libremente** [comment]
Make sense, go for it
