### ISSUE TITLE
Add pa11y-ci to the CI pipeline

### ISSUE THREAD

**Issue by bfabio** [italia/developers.italia.it#707]
Run accessibility tests in the CI pipeline against all the generated pages with https://www.npmjs.com/package/pa11y-ci.

**Comment by libremente** [comment]
True, we need this, however since there are many errors right now spread all over the pages I would give priority to the error fixing job and then later on we can try to set this up, if not we might have issues on every build.
`pa11y-ci` is cool since it works on sitemaps `-s developers.italia.it/sitemap.xml`. However there is also https://www.npmjs.com/package/pa11y which provides info on the single page and can be run locally.
